language: node_js
before_install: 
  - cd ./serve && npm install && npm start &
before_script: cd ./client && npm install
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run lint
  - npm rebuild node-sass
  - npm run build
before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
notifications:
    slack: top-banter:1WDCbLsEunsIUeZd3cXbPQJn